friendo/authentication/urls.py
from django.urls import path
import authentication.views as auth_views

# App Name
app_name = 'authentication'

urlpatterns = [
    path('register/', auth_views.register, name="register"),
    path('login/', auth_views.login, name="login"),
    path('logout/', auth_views.logout, name="logout"),
]

friendo/discover/urls.py
from django.urls import path
import discover.views as discover_views

# App Name
app_name = 'discover'

urlpatterns = [
    path('', discover_views.discover_home, name="discover_home"),
    path('friends/', discover_views.discover_friends, name="discover_friends"),
]

friendo/friendo/urls.py
# Django Imports
from django.contrib import admin
from django.urls import path, include # Used for importing from other URL files.
from django.conf.urls.static import static # Media Options
from django.conf import settings # Media Option

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('discover/', include('discover.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friendo/home/urls.py
from django.urls import path
import home.views as home_views

# App Name
app_name = 'home'

urlpatterns = [
    path('', home_views.home, name="home")
]

friendo/profiles/urls.py
from django.urls import path
import profiles.views as profile_views

# App Name
app_name = 'profiles'

urlpatterns = [
    path('', profile_views.my_profile, name="my_profile"),
    path('<int:profileID>', profile_views.profile, name="profile"),
    path('edit/', profile_views.edit_profile, name="edit"),
    path('hobbies/', profile_views.select_hobbies, name="select_hobbies"),
    path('interests/', profile_views.select_interests, name="select_interests"),
]

friendo/friendo/templates/external_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Friendo - {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
    {% block scripts %}
    {% endblock %}
</body>
</html>

friendo/friendo/templates/internal_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Friendo - {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@40,600,1,200" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head %}
    {% endblock %}
</head>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">
            <span class="friendo-brand">friendo</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'discover:discover_home' %}">Discover</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Messages</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profiles:my_profile' %}">Profile</a>
                </li>
            </ul>
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'authentication:logout' %}">Sign Out</a>
            </li>
        </ul>
      </div>
    </div>
</nav>
<body>
    {% block body %}
    {% endblock %}
    <script src="{% static 'js/activepage.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>