friendo/friendo/urls.py
# Django Imports
from django.contrib import admin
from django.urls import path, include # Used for importing from other URL files.
from django.conf.urls.static import static # Media Options
from django.conf import settings # Media Option

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('discover/', include('discover.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friendo/home/urls.py
from django.urls import path
import home.views as home_views

# App Name
app_name = 'home'

urlpatterns = [
    path('', home_views.home, name="home")
]

friendo/profiles/urls.py
from django.urls import path
import profiles.views as profile_views

# App Name
app_name = 'profiles'

urlpatterns = [
    path('', profile_views.my_profile, name="my_profile"),
    path('<int:profileID>', profile_views.profile, name="profile"),
    path('edit/', profile_views.edit_profile, name="edit"),
    path('hobbies/', profile_views.select_hobbies, name="select_hobbies"),
    path('interests/', profile_views.select_interests, name="select_interests"),
]

friendo/profiles/models.py
# Django Imports
from django.db import models
from django.contrib.auth.models import User

# Python3 Imports
from datetime import date # Used to calculate the user's age.

class Hobby(models.Model):
    '''Defines a Hobby model that represents a hobby. Users can have many of these listed.'''
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=400)
    icon = models.ImageField(default='default/placeholder.png', upload_to='hobby_interest_images')
    
    def __str__(self):
        return self.name
    
class Interest(models.Model):
    '''Defines an Interest model that represents an interest that a user can have.'''
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=200)
    icon = models.ImageField(default='default/placeholder.png', upload_to='hobby_interest_images')
    
    def __str__(self):
        return self.name

class Profile(models.Model):
    '''Defines a Profile model that stands in for the User model.
    
    This model is created mainly to "extend" the existing User model and add
    fields such as hobbies and birthdate.
    
    Attributes
    ----------
    user : OneToOneField
        A one-to-one connection with the Django user created for this profile.
    handle : CharField
        The user's "username", also known as handle, which other users can search for to find this user.
    birthday : datetime
        The user's birthdate.
    age : PositiveSmallIntegerField
        The user's current age; for now, calculated each time their profile is visited.
        
    Methods
    -------
    calculateAge : void
        Calculates the user's current age.
    '''
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    profile_image = models.ImageField(default='default/placeholder.png', upload_to='profile_images')
    location = models.CharField(max_length=200, default='friendo')
    bio = models.TextField(default="Tell us something about yourself!")
    birthday = models.DateField()
    age = models.PositiveSmallIntegerField()
    gender = models.CharField(max_length=50, blank=True)
    seeking_romance = models.BooleanField(default=False)
    hobbies = models.ManyToManyField(Hobby, related_name='profiles', blank=True)
    interests = models.ManyToManyField(Interest, related_name='profiles', blank=True)
    friends = models.ManyToManyField("self", related_name='friends', blank=True)
    following = models.ManyToManyField("self", related_name='followers', blank=True)
    first_visit = models.BooleanField(default=True)
    
    def __str__(self):
        return self.user.username
    
    def calculateAge(self):
        '''Calculates the user's current age.'''
        today = date.today()
        age = today.year - self.birthday.year - ((today.month, today.day) < (self.birthday.month, self.birthday.day))
        if age != self.age:
            self.age = age
            self.save()

friendo/profiles/forms.py
# Django Imports
from django import forms
from profiles.models import Profile

class UpdateProfileImageForm(forms.ModelForm):
    '''This form allows the user to update their profile picture.'''
    profile_image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control',
                                                           'type': 'file',
                                                           'id': 'formFile'}),
                                     label="Upload your new profile picture:",
                                     required=False)
    class Meta:
        model = Profile
        fields = ['profile_image']

friendo/profiles/views.py
# Django Imports
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required # Login decorator.

# Python3 Imports
import operator # For itemgetter mapping.

# Local Imports
from profiles.models import Hobby, Interest, Profile
from profiles.forms import UpdateProfileImageForm

@login_required
def my_profile(request):
    '''Displays the currently logged in user's profile.'''
    # Grab the current user's hobbies, interests, and groups.
    context = {}
    my_profile = Profile.objects.get(user=request.user)
    my_hobbies = my_profile.hobbies.all()
    my_interests = my_profile.interests.all()
    context['hobbies'] = my_hobbies
    context['interests'] = my_interests
    return render(request=request, template_name='profiles/my_profile.html', context=context)

@login_required
def profile(request, profileID):
    '''Displays another user's profile.'''
    context = {}
    profile = Profile.objects.get(id=profileID)
    hobbies = profile.hobbies.all()
    interests = profile.interests.all()
    following = True if profile in request.user.profile.following.all() else False
    
    if request.method == 'POST':
        # User is attempting to follow or unfollow this person.
        if following:
            request.user.profile.following.remove(profile)
            following = False
        else:
            request.user.profile.following.add(profile)
            following = True
            
    context['profile'] = profile
    context['following'] = following
    context['hobbies'] = hobbies
    context['interests'] = interests
    return render(request=request, template_name='profiles/profile.html', context=context)

@login_required
def edit_profile(request):
    '''The view that puts the user into edit mode on their profile.'''
    context = {}
    my_profile = Profile.objects.get(user=request.user)
    update_photo_form = UpdateProfileImageForm()
    
    if request.method == 'POST':
        # Check if user is changing their profile picture.
        if 'pictureChange' in request.POST:
            update_photo_form = UpdateProfileImageForm(request.POST, request.FILES, instance=my_profile)
            if update_photo_form.is_valid():
                update_photo_form.save()
                my_profile.save()
            return redirect('profiles:edit')
        else:
            # User is attempting to update their profile.
            new_first_name = request.POST.get('first_name', my_profile.user.first_name)
            new_last_name = request.POST.get('last_name', my_profile.user.last_name)
            new_location = request.POST.get('location', my_profile.location)
            new_bio = request.POST.get('bio', my_profile.bio)
            
            my_profile.user.first_name = new_first_name
            my_profile.user.last_name = new_last_name
            my_profile.user.save()
            my_profile.location = new_location
            my_profile.bio = new_bio
            my_profile.save()
            return redirect('profiles:my_profile')
    
    # If this is the user's first time editing their profile, get rid of their first_visit flag.
    my_profile.first_visit = False
    my_profile.save()
    my_hobbies = my_profile.hobbies.all()
    my_interests = my_profile.interests.all()
    context['hobbies'] = my_hobbies
    context['interests'] = my_interests
    context['form'] = update_photo_form
    return render(request=request, template_name='profiles/edit_profile.html', context=context)
    
@login_required
def select_hobbies(request):
    '''This is the page that will display all selectable hobbies for the purposed of updating one's profile.
    '''
    my_hobbies = request.user.profile.hobbies.all()
    if request.method == 'POST':
        # User is attempting to update their hobbies.
        # Get all of the hobbies they selected.
        post_data = list(request.POST.items())[1:]
        hobby_ids = list(map(operator.itemgetter(0), post_data))
        # Check if they have deselected a hobby they had previously saved.
        for hobby in my_hobbies:
            if hobby.id not in hobby_ids:
                request.user.profile.hobbies.remove(hobby)
        
        # Add the new hobbies
        for id in hobby_ids:
            hobby = Hobby.objects.get(id=id)
            request.user.profile.hobbies.add(hobby)
            
        # Redirect the user back to their profile!
        return redirect('profiles:my_profile')
        
    all_hobbies = Hobby.objects.all()
    return render(request=request, template_name='profiles/edit_hobbies.html', context={'all_hobbies': all_hobbies,
                                                                                   'my_hobbies': my_hobbies})
    
@login_required
def select_interests(request):
    '''This is the page that will display all selectable interests for the purposed of updating one's profile.
    '''
    my_interests = request.user.profile.interests.all()
    if request.method == 'POST':
        # User is attempting to update their interests.
        # Get all of the interests that they selected.
        post_data = list(request.POST.items())[1:]
        interest_ids = list(map(operator.itemgetter(0), post_data))
        # Check if they have deselected a hobby they had previously saved.
        for interest in my_interests:
            if interest.id not in interest_ids:
                request.user.profile.interests.remove(interest)
        
        # Add the new hobbies
        for id in interest_ids:
            interest = Interest.objects.get(id=id)
            request.user.profile.interests.add(interest)
            
        # Redirect the user back to their profile!
        return redirect('profiles:my_profile')
        
    all_interests = Interest.objects.all()
    return render(request=request, template_name='profiles/edit_hobbies.html', context={'all_hobbies': all_interests,
                                                                                   'my_hobbies': my_interests})

friendo/profiles/templates/profiles/edit_hobbies.html
{% extends 'internal_base.html' %}
{% block title %}Hobbies{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row site-banner" style="padding: 75px;">
        <h2 class="text-center p-0">Hobby Catalog</h2>
        <p class="text-center">Here is a list of all of the wonderful hobbies available on friendo. Pick as many as you'd like!</p>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="btn-group hobby-list mt-3">
                    {% for hobby in all_hobbies %}
                        {% if hobby in my_hobbies %}
                            <span class="m-2">
                                <input type="checkbox" class="btn-check" id="{{ hobby.id }}" name="{{ hobby.id }}" checked autocomplete="off">
                                <label class="btn btn-light btn-lg" for="{{ hobby.id }}">{{ hobby.name }}</label>
                            </span>
                        {% else %}
                            <span class="m-2">
                                <input type="checkbox" class="btn-check" id="{{ hobby.id }}" name="{{ hobby.id }}" autocomplete="off">
                                <label class="btn btn-light btn-lg" for="{{ hobby.id }}">{{ hobby.name }}</label>
                            </span>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="d-flex fixed-bottom justify-content-end m-3">
            <button type="submit" class="btn btn-primary mt-3" value="Submit">
                Submit
                <span class="material-symbols-rounded" style="font-size: 1rem !important;">save</span>
            </button>
        </div>
    </form>    
</div>
{% endblock %}

friendo/profiles/templates/profiles/edit_interests.html
{% extends 'internal_base.html' %}
{% block title %}Interests{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row site-banner" style="padding: 75px;">
        <h2 class="text-center p-0">Interest Catalog</h2>
        <p class="text-center">Here is a list of all of the interests available on friendo. Pick as many as you'd like!</p>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="btn-group interest-list mt-3">
                    {% for interest in all_interests %}
                        {% if interest in my_interests %}
                            <span class="m-2">
                                <input type="checkbox" class="btn-check" id="{{ interest.id }}" name="{{ interest.id }}" checked autocomplete="off">
                                <label class="btn btn-light btn-lg" for="{{ interest.id }}">{{ interest.name }}</label>
                            </span>
                        {% else %}
                            <span class="m-2">
                                <input type="checkbox" class="btn-check" id="{{ interest.id }}" name="{{ interest.id }}" autocomplete="off">
                                <label class="btn btn-light btn-lg" for="{{ interest.id }}">{{ interest.name }}</label>
                            </span>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="d-flex fixed-bottom justify-content-end m-3">
            <button type="submit" class="btn btn-primary mt-3" value="Submit">
                Submit
                <span class="material-symbols-rounded" style="font-size: 1rem !important;">save</span>
            </button>
        </div>
    </form>    
</div>
{% endblock %}

friendo/profiles/templates/profiles/edit_profile.html
{% extends 'internal_base.html' %}
{% block title %}My Profile{% endblock %}
{% block body %}
<form method="POST" id="editForm">
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row site-banner" style="padding: 100px; background-position: right !important;">
        </div>
        <div class="row">
            <div class="col-3 ms-3">
                <div class="row">
                    <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#pictureModal">
                        <img src="{{ user.profile.profile_image.url }}" class="img-thumbnail mx-auto profile-img">
                    </button>
                </div>
                <div class="row border-bottom mx-3">
                    <input type="text" class="form-control-lg my-1 text-center" id="first_name" name="first_name" value="{{ user.first_name }}">
                    <input type="text" class="form-control-lg my-1 text-center" id="first_name" name="last_name" value="{{ user.last_name }}">
                    <small class="text-center mb-2">@{{ user.username }}</small>
                </div>
                <div class="row px-3">
                    <div class="d-flex justify-content-center my-2">
                        <span class="material-symbols-rounded">location_on</span>
                        <input type="text" class="form-control text-center" id="location" name="location" value="{{ user.profile.location }}">
                    </div>
                    <div class="d-flex justify-content-center">
                        <textarea class="form-control" id="bio" name="bio" rows="3">{{ user.profile.bio }}</textarea>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="row mt-3">
                    <div class="col">
                        <h4 class="text-center">Hobbies</h4>
                        {% if hobbies %}
                            {% for hobby in hobbies %}
                                <div class="row justify-content-center mb-1">
                                    <div class="card text-center w-75 p-0">
                                        <div class="card-body">
                                            <h5 class="card-title m-0">{{ hobby.name }}</h5>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="row justify-content-center">
                            <button type="button" class="card btn w-75 p-0" data-bs-toggle="modal" data-bs-target="#hobbyModal">
                                <div class="card-body text-center">
                                    <img class="card-img-top" src="https://images.squarespace-cdn.com/content/v1/56e19ec5e3214084d69d4b7d/1473524254173-BGV5W2Z5FM46F67SYZHJ/PlusIcon_Small_Gray.png" style="height: 50px; width: 50px;" alt="Add Item">
                                </div>
                            </button>
                        </div>
                    </div>
                    <div class="col">
                        <h4 class="text-center">Interests</h4>
                        {% if interests %}
                            {% for interest in interests %}
                                <div class="row justify-content-center mb-1">
                                    <div class="card text-center w-75 p-0">
                                        <div class="card-body">
                                            <h5 class="card-title m-0">{{ interest.name }}</h5>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="row justify-content-center">
                            <button type="button" class="card btn w-75 p-0" data-bs-toggle="modal" data-bs-target="#interestModal">
                                <div class="card-body text-center">
                                    <img class="card-img-top" src="https://images.squarespace-cdn.com/content/v1/56e19ec5e3214084d69d4b7d/1473524254173-BGV5W2Z5FM46F67SYZHJ/PlusIcon_Small_Gray.png" style="height: 50px; width: 50px;" alt="Add Item">
                                </div>
                            </button>
                        </div>
                    </div>
                    <div class="col">
                        <h4 class="text-center">Groups</h4>
                        {% if groups %}
                            {% for group in groups %}
                                <div class="row justify-content-center mb-1">
                                    <div class="card btn text-center w-75 p-0">
                                        <div class="card-body">
                                            <h5 class="card-title m-0">{{ group.name }}</h5>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="text-center">Looks like there's nothing here yet. Go to the Discover tab to join some groups!</div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex fixed-bottom justify-content-end m-3">
            <button type="submit" form="editForm" class="btn btn-light mt-3" value="Submit">
                Save
                <span class="material-symbols-rounded" style="font-size: 1rem !important;">save</span>
            </button>
        </div>
    </div>
</form>

<div class="modal fade" id="pictureModal" tabindex="-1" aria-labelledby="pictureModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fs-5" id="pictureModalLabel">Change Profile Picture</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form enctype="multipart/form-data" id="changePhoto" method="POST">
                    {% csrf_token %}
                    <div class="mb-3 form-group">
                        {% for field in form %}
                            <label for="formFile" class="form-label">{{ field.label }}</label>
                            {{ field }}
                        {% endfor %}
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary" data-bs-dismiss="modal" form="changePhoto" name="pictureChange">Submit</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="hobbyModal" tabindex="-1" aria-labelledby="hobbyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fs-5" id="hobbyModalLabel">Before you go...</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Leaving this page will discard any other changes you've made to your name, location, and/or bio. Are you sure you want to continue?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
                <a type="button" class="btn btn-warning" href="{% url 'profiles:select_hobbies' %}">Continue</a>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="interestModal" tabindex="-1" aria-labelledby="interestModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fs-5" id="hobbyModalLabel">Before you go...</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Leaving this page will discard any other changes you've made to your name, location, and/or bio. Are you sure you want to continue?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
                <a type="button" class="btn btn-warning" href="{% url 'profiles:select_interests' %}">Continue</a>
            </div>
        </div>
    </div>
</div>
  
{% endblock %}

friendo/profiles/templates/profiles/hobbies.html
{% extends 'internal_base.html' %}
{% block title %}Hobbies{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row" style="padding: 75px; background-color: grey; color:white;">
        <h2 class="text-center p-0">Hobby Catalog</h2>
        <p class="text-center">Here is a list of all of the wonderful hobbies available on friendo. Pick as many as you'd like!</p>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="btn-group hobby-list mt-3">
                    {% for hobby in all_hobbies %}
                        {% if hobby in my_hobbies %}
                            <span class="m-2">
                                <input type="checkbox" class="btn-check" id="{{ hobby.id }}" name="{{ hobby.id }}" checked autocomplete="off">
                                <label class="btn btn-light btn-lg" for="{{ hobby.id }}">{{ hobby.name }}</label>
                            </span>
                        {% else %}
                            <span class="m-2">
                                <input type="checkbox" class="btn-check" id="{{ hobby.id }}" name="{{ hobby.id }}" autocomplete="off">
                                <label class="btn btn-light btn-lg" for="{{ hobby.id }}">{{ hobby.name }}</label>
                            </span>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="d-flex fixed-bottom justify-content-end m-3">
            <button type="submit" class="btn btn-primary mt-3" value="Submit">
                Submit
                <span class="material-symbols-rounded" style="font-size: 1rem !important;">save</span>
            </button>
        </div>
    </form>    
</div>
{% endblock %}

friendo/profiles/templates/profiles/my_profile.html
{% extends 'internal_base.html' %}
{% load static %}
{% block title %}My Profile{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row site-banner" style="padding: 100px; background-position: right !important;">
    </div>
    <div class="row">
        <div class="col-3 ms-3">
            <div class="row">
                <img src="{{ user.profile.profile_image.url }}" class="img-thumbnail mx-auto profile-img">
            </div>
            <div class="row border-bottom mx-3">
                <h4 class="text-center mt-2 mb-0">{{ user.first_name }} {{ user.last_name }}</h4>
                <small class="text-center">@{{ user.username }}</small>
                <small class="text-center mb-2">{{ user.profile.gender }}, {{ user.profile.age }}</small>
            </div>
            <div class="row px-3 mx-3 pb-1 border-bottom">
                <div class="d-flex justify-content-center mt-2">
                    <span class="material-symbols-rounded home-symbol me-1">location_on</span>
                    <span class="my-auto">{{ user.profile.location }}</span>
                </div>
                <div class="d-flex justify-content-center">
                    {% if user.profile.seeking_romance is True %}
                        <span class="material-symbols-rounded home-symbol me-1">favorite</span>
                        <span class="my-auto">Looking for Romance</span>
                    {% else %}
                        <span class="material-symbols-rounded home-symbol me-1">mood</span>
                        <span class="my-auto">Looking for Friends</span>
                    {% endif %}
                </div>
            </div>
            <div class="row- px-3 mx-3 pt-2">
                <div class="d-flex justify-content-center">
                    {{ user.profile.bio }}
                </div>
            </div>
        </div>
        <div class="col">
            <div class="row mt-3">
                <div class="col">
                    <h4 class="text-center">Hobbies</h4>
                    {% if hobbies %}
                        {% for hobby in hobbies %}
                            <div class="row justify-content-center mb-1">
                                <div class="card text-center w-75 p-0">
                                    <div class="card-body">
                                        <h5 class="card-title m-0">{{ hobby.name }}</h5>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="text-center">Looks like there's nothing here yet. Edit your profile to add some hobbies.</div>
                    {% endif %}
                </div>
                <div class="col">
                    <h4 class="text-center">Interests</h4>
                    {% if interests %}
                        {% for interest in interests %}
                            <div class="row justify-content-center mb-1">
                                <div class="card text-center w-75 p-0">
                                    <div class="card-body">
                                        <h5 class="card-title m-0">{{ interest.name }}</h5>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="text-center">Looks like there's nothing here yet. Edit your profile to add some interests.</div>
                    {% endif %}
                </div>
                <div class="col">
                    <h4 class="text-center">Groups</h4>
                    {% if groups %}
                        {% for group in groups %}
                            <div class="row justify-content-center mb-1">
                                <div class="card btn text-center w-75 p-0">
                                    <div class="card-body">
                                        <h5 class="card-title m-0">{{ group.name }}</h5>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="text-center">Looks like there's nothing here yet. Go to the Discover tab to join some groups!</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="d-flex fixed-bottom justify-content-end m-3">
        <a class="btn btn-light mt-3" href="{% url 'profiles:edit' %}">
            Edit Profile
            <span class="material-symbols-rounded" style="font-size: 1rem !important;">save</span>
        </a>
    </div>
</div>

<div class="modal fade" id="firstVisitModal" tabindex="-1" aria-labelledby="firstVisitModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fs-5" id="firstVisitModalLabel">Welcome to your profile!</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                This is the heart of your friend-finding on friendo. Here, you can tell us all about your hobbies and
                interests so that we can connect you to people just like you.<br><br>
                To get started, click the <b>Edit Profile</b> button in the bottom right-hand corner of the page.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Got It!</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    {% if user.profile.first_visit %}
        <script src="{% static 'js/first_visit_modal.js' %}"></script>
    {% endif %}
{% endblock %}