friendo/discover/urls.py
from django.urls import path
import discover.views as discover_views

# App Name
app_name = 'discover'

urlpatterns = [
    path('', discover_views.discover_home, name="discover_home"),
    path('friends/', discover_views.discover_friends, name="discover_friends"),
]

friendo/friendo/urls.py
# Django Imports
from django.contrib import admin
from django.urls import path, include # Used for importing from other URL files.
from django.conf.urls.static import static # Media Options
from django.conf import settings # Media Option

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('discover/', include('discover.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friendo/home/urls.py
from django.urls import path
import home.views as home_views

# App Name
app_name = 'home'

urlpatterns = [
    path('', home_views.home, name="home")
]

friendo/profiles/urls.py
from django.urls import path
import profiles.views as profile_views

# App Name
app_name = 'profiles'

urlpatterns = [
    path('', profile_views.my_profile, name="my_profile"),
    path('<int:profileID>', profile_views.profile, name="profile"),
    path('edit/', profile_views.edit_profile, name="edit"),
    path('hobbies/', profile_views.select_hobbies, name="select_hobbies"),
    path('interests/', profile_views.select_interests, name="select_interests"),
]

friendo/discover/models.py
from django.db import models

# Create your models here.

friendo/discover/views.py
# Django Imports
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required # Login decorator.
from django.db.models import Q # Used for filtering down objects.

# Local Imports
from profiles.models import Profile

# Python3 Imports
from operator import itemgetter # Used for more efficient sorting.

@login_required
def discover_home(request):
    '''The landing page of the Discover part of friendo.'''
    return render(request=request, template_name='discover/discover_home.html')

@login_required
def discover_friends(request):
    '''This is the starting page of the Discover Friends feature.'''
    context = {}
    if request.method == 'POST':
        # Get fields from POST request here. Some minor processing to convert strings to bools done here.
        options = {}
        options['filter_romance'] = True if request.POST.get('seeking_romance', 'off') == 'on' else False
        preferred_gender = request.POST.get('gender', None)
        options['preferred_gender'] = None if preferred_gender == 'None' else preferred_gender
        min_age = request.POST.get('min_age', None)
        options['min_age'] = None if min_age == '' else min_age
        max_age = request.POST.get('max_age', None)
        options['max_age'] = None if max_age == '' else max_age
        options['location_on'] = True if request.POST.get('location_on', None) == 'on' else False
        context['filter'] = options
        context['results'] = filterFriends(options=options, requestProfile=request.user.profile)
        context['results'] = rankFriendsByMatchScore(context['results'], requestProfile=request.user.profile)
        
    return render(request=request, template_name='discover/discover_friends.html', context=context)

def filterFriends(options, requestProfile):
    '''This function performs the user filtering for the Discover Friends feature.
    '''
    friend_pool = Profile.objects.all()
    # This line ensures that the user is not included in their search results.
    friend_pool = friend_pool.filter(~Q(id=requestProfile.id))
    
    # Filtering based on the options given.
    if options['filter_romance'] is True:
        friend_pool = friend_pool.filter(seeking_romance=False)
    if options['preferred_gender'] is not None:
        friend_pool = friend_pool.filter(gender=options['preferred_gender'])
        
    if options['min_age'] is not None:
        friend_pool = friend_pool.filter(age__gte=options['min_age'])
        
    if options['max_age'] is not None:
        friend_pool = friend_pool.filter(age__lte=options['max_age'])
        
    if options['location_on']:
        friend_pool = friend_pool.filter(location__icontains=requestProfile.location)
        
    return friend_pool

def rankFriendsByMatchScore(results, requestProfile):
    '''This function ranks the user's friend search results by their match score and sorts them in descending order.
    
    Match score is calculate based on how many hobbies and interests the two users share.
    '''
    # The match score is essentially the number of connection points the two contacts share divided by the total number of
    # possible connections between the two (hobbies + interests).
    ranked_results = []
    my_hobbies = requestProfile.hobbies.all()
    my_interests = requestProfile.interests.all()
    # Calculate how many connection points are available for me.
    my_available_points = len(my_hobbies) + len(my_interests)

    if my_available_points != 0:
        for candidate in results:
            # Collect the hobbies and interests of the candidate.
            their_hobbies = candidate.hobbies.all()
            their_interests = candidate.interests.all()
            
            connectionPoints = 0
            availablePoints = my_available_points
            for hobby in their_hobbies:
                if hobby in my_hobbies:
                    connectionPoints += 1
                else:
                    availablePoints += 1
                    
            for interest in their_interests:
                if interest in my_interests:
                    connectionPoints += 1
                else:
                    availablePoints += 1
            
            # Do final calculation + rounding.
            score = 0
            if connectionPoints != 0:
                score = round((connectionPoints / availablePoints) * 100.0)

            ranked_results.append((candidate, score))
            
        ranked_results = sorted(ranked_results, key=itemgetter(1), reverse=True)
    else:
        for candidate in results:
            ranked_results.append((candidate, 0))
            
    return ranked_results
        
    # Lastly, rank candidates by match score, descending.
    
    

friendo/discover/templates/discover/discover_friends.html
{% extends 'internal_base.html' %}
{% block title %}Discover{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row site-banner" style="padding: 75px;">
        <h2 class="text-center p-0">Discover Friends</h2>
        <p class="text-center">friendo works to connect you with people who best match your hobbies and interests.
            You can also decide which type of people you're most interested in connecting with.
        </p>
    </div>
    <div class="row mt-3">
        <div class="col-4">
            <div class="row text-center border-bottom mx-3">
                <h3 class="text-center">Filters</h3>
                <small class="mb-3">These filters can help you find the friends that best fit you.</small>
            </div>
            <div class="row mt-3">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-check form-switch d-flex justify-content-center mb-3">
                        <input class="form-check-input me-3" {% if filter.filter_romance is True %}checked{% endif %} type="checkbox" role="switch" id="seeking_romance" name="seeking_romance">
                        <label class="form-check-label" for="seeking_romance">Filter Out People Seeking Romance</label>
                    </div>
                    <div class="form-check form-switch d-flex justify-content-center mb-3">
                        <input class="form-check-input me-3" {% if filter.location_on %}checked{% endif %} type="checkbox" role="switch" id="location_on" name="location_on">
                        <label class="form-check-label" for="location_on">Find People Near Me</label>
                    </div>
                    <div class="d-flex justify-content-center align-content-center mb-3">
                        <label class="form-check-label me-3" for="gender">Preferred Gender</label>
                        <select class="form-select form-select-sm w-50" id="gender" name="gender" aria-label="Preferred Gender">
                            <option {% if filter is None or filter.preferred_gender is None %}selected{% endif %} value="None">None</option>
                            <option {% if filter.preferred_gender == "Female" %}selected{% endif %} value="Female">Female</option>
                            <option {% if filter.preferred_gender == "Male" %}selected{% endif %} value="Male">Male</option>
                            <option {% if filter.preferred_gender == "Transgender" %}selected{% endif %} value="Transgender">Transgender</option>
                            <option {% if filter.preferred_gender == "Non-Binary" %}selected{% endif %} value="Non-Binary">Non-Binary</option>
                            <option {% if filter.preferred_gender == "Gender-Fluid" %}selected{% endif %} value="Gender-Fluid">Gender-Fluid</option>
                        </select>
                    </div>
                    <div class="d-flex justify-content-center align-content-center mb-3">
                        <label class="form-check-label me-3" for="min_age">Preferred Age</label>
                        <input class="form-control form-control-sm w-25 text-center" value="{% if filter.min_age is not None %}{{ filter.min_age }}{% endif %}" name="min_age" type="text" aria-label="Preferred Minimum Age">
                        <label class="form-check-label mx-3" for="max_age">to</label>
                        <input class="form-control form-control-sm w-25 text-center" value="{% if filter.max_age is not None %}{{ filter.max_age }}{% endif %}" name="max_age" type="text" aria-label="Preferred Maximum Age">
                    </div>
                    <div class="d-flex justify-content-center align-content-center my-3">
                        <button type="submit" class="btn btn-primary w-50 m-3">Search</button>
                    </div>
                </form>
            </div> 
        </div>
        <div class="col discover-friend-results">
            {% if results is not None %}
                {% if results %}
                    <div class="row row-cols-4">
                        {% for result in results %}
                            <div class="card discover-friend-result-card m-1" style="width: 13rem;">
                                <img src="{{ result.0.profile_image.url }}" class="card-img-top discover-profile-img img-thumbnail" alt="The profile image of {{ result.0.user.first_name }}">
                                <div class="card-body text-center">
                                    <h5 class="card-title">{{ result.0.user.first_name }} {{ result.0.user.last_name }}</h5>
                                    <small>Match Score:</small>
                                    <p class="display-6 card-text">{{ result.1 }}%</p>
                                    <a href="{% url 'profiles:profile' result.0.id %}" class="stretched-link"></a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>    
                {% else %}
                    <p>It looks like your search didn't yield any results.</p>
                {% endif %}
            {% else %}
                <p class="text-center" style="color: grey;">Use the filter on the left to tell us a little about the friends that you're looking for.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

friendo/discover/templates/discover/discover_home.html
{% extends 'internal_base.html' %}
{% block title %}Discover{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row site-banner" style="padding: 75px;">
        <h2 class="text-center p-0">Discover</h2>
        <p class="text-center">Discover people just like you and make connections that can last a lifetime.</p>
    </div>
    <!-- Discover Start -->
    <div class="row align-items-center justify-content-center mt-3">
        <div class="col-5">
            <div class="discover-card card text-center">
                <img src="/media/default/friend.jpg" style="object-position: 50% 25%;" class="card-img-top" alt="Two happy friends hugging each other.">
                <div class="card-body">
                    <h2 class="card-title">Discover Friends</h2>
                    <p class="card-text">I'm looking for a one-to-one connection.</p>
                    <a href="{% url 'discover:discover_friends' %}" class="btn btn-primary w-75">Start</a>
                </div>
            </div>
        </div>
        <div class="col-5">
            <div class="discover-card card text-center">
                <img src="/media/default/friend_grp.jpg" style="object-position: 50% 75%;" class="card-img-top" alt="A group of friends adventuring in a rocky wilderness.">
                <div class="card-body">
                    <h2 class="card-title">Discover Groups</h2>
                    <p class="card-text">I'm looking to join a group of like-minded individuals.</p>
                    <a href="#" class="btn btn-primary w-75 disabled">Coming Soon</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}